### ISSUE TITLE
Audience UI

### ISSUE THREAD

**Issue by roborourke** [humanmade/analytics#19]
The audience UI for analytics would be an interface on top of Pinpoint's audience segments.

We can provide an interface similar to that in Pinpoint whereby users can select from some filters based on the endpoint or user data eg. operating system / locale to create named segments. These segments could then be applied for any general analytics data we gather and display, additionally the segments could be used for features including:

- campaigns / push notifications
- experience blocks
- experiments

This is the pinpoint console UI for creating segments based on behaviours like activity and further filtering by endpoint attributes and demographics. I'm not sure if it allows you to use user attributes for filtering too.

![console aws amazon com_pinpoint_home__region=us-east-1](https://user-images.githubusercontent.com/23417/62117278-8ca4a000-b2b3-11e9-9c3f-f02203a6856d.png)

**Comment by joehoyle** [comment]
Interesting, could we use this (actual UI) as a first EB "DMP"? cc @elodiebouneau ?

**Comment by grarighe** [comment]
I've added some examples of audience management features [in this doc](https://docs.google.com/document/d/1VoNG1a9fshULgWQ4iB7Wyv_Yab3Hxg8Wws1IAncBtwA/edit#). There is so much to go through that I thought I'd share it in the meantime. You can also see examples of UI.

**Comment by roborourke** [comment]
@grarighe thanks for this, we went over it all yesterday and have some good ideas to move forward with, will be an update soon

**Comment by elodiebouneau** [comment]
@roborourke and I had a productive call yesterday to go over the details of audience UI. I will post notes and wireframes in the next couple of days to summarize our thoughts

**Comment by elodiebouneau** [comment]
Here is the draft mockup from our call @roborourke 

![Experience Blocks - Audience Creation - Window@2x](https://user-images.githubusercontent.com/7881431/71876336-59283600-30db-11ea-8765-0dd34ba8de50.png)

A few notes:
- Title and Description should have max characters.
- Ability to select 2 audiences in the GB interface
- The order of the audiences expresses precedence if a user is in 2 difference audiences and they are both used in the same zone
- Audience names are unique; Descriptions are not.
- When user clicks on "edit" or "delete" and the audience is in use, a warning should be shown to let them know what will happen to the "experiences" currently on.

**List of Rules we talked about:**
- Client time
- Location 
- OS
- Browser
- Device
- External Campaign
- UTM
- First-time visitor
- Phase next: Pluggable sources (Weather, etc)

Remaining questions I would love your opinion on:
1. Should we put an audience size estimate in the main table?
2. Should we be able to "browse" old audience versions?
3. Should we have premade audiences? If so, which?

**Comment by elodiebouneau** [comment]
@roborourke What do you think? How can we make this better? Is there anything not needed? Anything missing?

**Comment by roborourke** [comment]
One idea I'd like to explore is how the interface could work in a similar way to the media modal popup. This would allow users to create and edit audiences in context whether it's in the gutenberg editor creating an experience block or the main audience management section.

> Ability to select 2 audiences in the GB interface

Can you elaborate on this a bit regarding the context? I'm not sure we need to worry about this just yet, at least in the scope of this issue.

To answer your questions:

> Should we put an audience size estimate in the main table?

Yeah, if we have that data cached. We can update the estimates async on a schedule.

> Should we be able to "browse" old audience versions?

Not directly as it'd be too much data, perhaps just from the specific audience edit screen.

> Should we have premade audiences? If so, which?

I think it's too early to tell. We could perhaps make a way to configure / register audiences through code though.

----------------

Re the mockup I think it captures the raw data and UI ok.

- showing the audience version is a really nice touch! I'd probably just do a number eg 1, 2, 3 as it'll be generated rather than explicitly written by someone
- we should probably make the "Add rule" link into a button, can iterate on that with some user tests
- I'm a bit worried the UI is squashed in that column, having more space would allow us to be more flexible and accommodate future changes more easily in a visually cleaner way
- given we'll likely store audiences as a post type to take advantage of revisions it'll be easier to use that as the default WP UI I think. The way audiences will be selected shouldn't be affected - I don't think we'd be using the default taxonomy picker at any rate

Cheers for pushing this forward. Going to research the Pinpoint audiences API some more to see if it's worth storing things there or if we'll have more flexibility rolling our own.

**Comment by elodiebouneau** [comment]
@karenames has been working on an update
![Audience UI - Experience Blocks - Window@2x](https://user-images.githubusercontent.com/7881431/73295691-281cbc00-41d6-11ea-8fa7-f61b1a8f6ab8.png)

**Comment by karenames** [comment]
I've worked on this a bit and tried to integrate your suggestions 
@roborourke could you take a look at it and let me know your thoughts?  I will then continue updating
https://whimsical.com/65bC9F8LJg3SqucvQ5jddK

**Comment by goldenapples** [comment]
This is looking really good! A few suggestions

In the list table, I think the "Last Modified" field is much less interesting to users than showing metrics about the audience, Depending on what's going to be available in the first release, could it show one of these instead of Last Modified:
* audience size (either the raw numbers, or graphs showing things like current percentage of user base, or growth over time)
* comparison to baseline in any vanity metrics available
* number of experiences served, or experiment results

I wonder if it's feasible to also show the actual audience definition logic, something like
> Device == **laptop** AND  Country == **Australia**

rather than depending on the user-supplied Description field.

I like the Edit Screen UI a lot, especially expanded like in the last Whimsical sketch. Actually, seeing the UI with that much space makes me think it would work well as a block editor interface. Is it worth mocking these audience selectors up as Gutenberg blocks to see what can be done graphically with them? 

(Apologies for the drive-by comment, I was just reading through the issue and wanted to offer some suggestions!)

**Comment by roborourke** [comment]
Thanks @karenames, looking good so far. I left a few comments on whimsical. It'd be good to add screenshots of that to this issue too to provide context in case the whimsical link is ever password protected or moved.

Agree with @goldenapples's comments in general too. Re:

> I wonder if it's feasible to also show the actual audience definition logic, something like
>> `Device == laptop AND Country == Australia`

I think this would potentially be a lot of info to show in the table for a complicated audience definition, plus we'd need to make the presentation non technical ideally, avoiding `==` etc. I think for the MVP we can leave that for now and see what feedback we get from early adopters.

@goldenapples there are mockups for the gutenberg implementation on a separate spreadsheet @elodiebouneau and @PriyaBhatia0210 have been working on but the focus here is just on creating audiences. We'll likely integrate that with gutenberg as a media modal style pop up to let the UI breathe.

**Comment by karenames** [comment]
Thanks @roborourke and @goldenapples!  I replied to your comments on whimsical Rob, with some further inquiry.

>It'd be good to add screenshots of that to this issue too to provide context in case the whimsical link is ever password protected or moved.
> 

Did you mean screenshots of the comments?

**Comment by roborourke** [comment]
@karenames sorry, screenshots of the mockups like in @elodiebouneau's comment here https://github.com/humanmade/analytics/issues/19#issuecomment-579401502

You can click on the paper aeroplane icon in the top bar and select "copy image" then right click on the image to save it to your computer, then you can upload it here.

**Comment by karenames** [comment]
Re:
>one of these instead of Last Modified:
> 
> * audience size (either the raw numbers, or graphs showing things like current percentage of user base, or growth over time)
> * comparison to baseline in any vanity metrics available
> * number of experiences served, or experiment results
> 
Any suggestions on which we're able or would best like to show?

I have this so far:
![image](https://user-images.githubusercontent.com/58703240/73563295-ffd9cb00-442a-11ea-94d6-debe14ac6cd2.png)

**Comment by goldenapples** [comment]
> Any suggestions on which we're able or would best like to show?

I see you're discussing this on Whimsical already, but I'd assume the "40 daily / 200 weekly users" would have to be available at first, as would a figure like "12% of total users".

> there are mockups for the gutenberg implementation on a separate spreadsheet @elodiebouneau and @PriyaBhatia0210 have been working on but the focus here is just on creating audiences

Makes sense, I was just thinking how the whole audience creation UI would work really well as a block editor interface, makes sense it would already be in progress.

**Comment by karenames** [comment]
So this is one option for the "Audience Size" column:
<img width="916" alt="Screen Shot 2020-01-31 at 5 07 39 PM" src="https://user-images.githubusercontent.com/58703240/73577918-54da0900-444c-11ea-91ce-3ab3c4560677.png">

...or just numbers:
<img width="884" alt="Screen Shot 2020-01-31 at 5 05 14 PM" src="https://user-images.githubusercontent.com/58703240/73577938-60c5cb00-444c-11ea-80f9-417236ce5069.png">

**Comment by karenames** [comment]
This is also what I have overall:

![image](https://user-images.githubusercontent.com/58703240/73577982-87840180-444c-11ea-9888-8009e46a326f.png)

Thanks so much for the feedback!

**Comment by roborourke** [comment]
I think this captures enough to start building for now and we can gather more feedback as we go. Thanks for the ideas and input so far everyone, I'm not sure how much we can really do for this MVP but they're useful suggestions so keep them coming.

**Comment by elodiebouneau** [comment]
Latest iterations are here: https://docs.google.com/presentation/d/1fBp_3XbKJQeNyvoF9fWWF2_hsmfkO5lXVBmRv8SKgzk/edit#slide=id.g7d019d3d4c_0_5

**Comment by roborourke** [comment]
Work in progress on #36 so far. About to start on adding some API endpoints to fetch audience estimates.

<img width="974" alt="Screenshot 2020-03-04 16 37 29" src="https://user-images.githubusercontent.com/23417/75904805-c3d7c280-5e3b-11ea-9d27-3ac6f14da57b.png">

**Comment by roborourke** [comment]
Currently have the elasticsearch queries all hooked up for this and ready for initial review. I'm going to spin off some additional issues now that there's an MVP to start testing and playing with.

<img width="1274" alt="Audience editor" src="https://user-images.githubusercontent.com/23417/76321886-8dd28c80-62da-11ea-9bca-f91fa25509e1.png">

<img width="1275" alt="Audience listing" src="https://user-images.githubusercontent.com/23417/76321905-94f99a80-62da-11ea-93da-82d6141dfe03.png">

**Comment by elodiebouneau** [comment]
@AnaFranciscaS This is the issue regarding the Audience Building feature.

Name in the PT/BV: Standalone Audience Creation
It is a Feature. Nothing like that is included in Vanilla WP.

**Definition:** This feature enables users to create audiences ie. groups of users that can then be served with specific content and later on with campaigns and a/b (we'll look at tackling those later this year). Users can use the criteria coming from our native analytics layer to easily and, without any engineering experience, create audiences. 

**Benefit:** Easy, self-contained audience creation. No need to integrate other tools to get going. (note: we'll open up the capability to include other tools in the future too). No technical knowledge required. 

**Business Value:** User can leverage his own native data to create audiences without any other tool and can enable non-technical users to create, manage and use audiences very easily so that targeted experiences can be created.
