### ISSUE TITLE
Performance: Caching and size reduction for analytics.js

### ISSUE THREAD

**Issue by roborourke** [humanmade/analytics#25]
We need to trim down the initial analytics.js bundle because it's a blocking script and loaded very early.

We ideally need to keep the early loading as the experiments plugin relies on it and we want our custom components to render immediately.

Possible approaches could involve one or more of the following:

- Rewrite everything to use vanilla JS and zero (or minimal) dependencies
- Lambda@Edge function to inline script
  - Follow strategy here: https://www.filamentgroup.com/lab/inlining-cache.html
  - Service worker cache inlined file
  - Set cookie
  - Bypass in lambda if cookie set
- Always inline the script 😱 ~40kb added to pages
- Use async and provide an alternative way to load/queue dependencies (maybe https://github.com/filamentgroup/loadJS)

**Comment by joehoyle** [comment]
What, fundamentally, is the dependency? As I understand it, we don't need analytics to do the ab-test switch, it's just the tracking, so we should be able to come up with an async approach to that callback/registration? I'm thinking this is more of an implementation decision that makes it a dep, than a hard requirement?

**Comment by roborourke** [comment]
Right now these two lines:

https://github.com/humanmade/experiments/blob/master/src/experiments.js#L175

https://github.com/humanmade/experiments/blob/master/src/experiments.js#L233

The first one is really key to how we query the data later on. I'll have a think about how it can be rewritten.

**Comment by roborourke** [comment]
Gonna make the registerAttributes & metrics functions sit on the global `Analytics` var, that _should_ be enough to support `async` on the script tag. If we don't care too much about accurately recording time on page we can defer it too or even load it in the footer.
