### ISSUE TITLE
Create dummy data helper

### ISSUE THREAD

**Issue by rmccue** [humanmade/analytics#57]
For demoing features, we should have the ability to use dummy data. This can be reused for testing as well. Essentially, we want a standard set of events, with the main difference being the timestamp (given the audience selector uses data from the last week).

We could probably reuse this for testing as well, as we want stable events there too.

Two main approaches I can see here:
* Insert dummy events into the ES database after clicking a button/running a command/etc. This works, but would need to be done every time you need more data. It does mean we can use ES for querying though.
* Stub out ES with a fake DB that returns (consistent) dummy data. Doesn't need regenerating, but does require us to reimplement ES' querying, which isn't great.

**Comment by roborourke** [comment]
Option 2 feels like a no go as the query DSL is super complicated. 

I think we could achieve the latter with a combination of `local-pinpoint` for recording the queries that write data to ES to a file that's mounted and doing some preprocessing on the time stamps in a WP CLI script or just in PHP. If it's a button you could get a timeout unless the amount of data is very very reasonable.

**Comment by roborourke** [comment]
Created this plugin to help with adding dummy data for now:

https://github.com/humanmade/altis-analytics-demo-tools
